[theme]
# Primary accent for interactive elements
primaryColor = '#3b66c4'

# Background color for the main content area
backgroundColor = '#c7dfe1'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F0F2F6'

# Color used for almost all text
textColor = '#00000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"